### ISSUE TITLE
Account Token

### ISSUE THREAD

**Issue by floofydoug** [Kloudless/meeting-scheduler#4]
I can't seem to get an account token when using the meeting-scheduler. I was able to get them when i hosted my own OAuth, but when I set up this listener: 

```        
scheduler.on('connectAccount', async eventData => {
            const options = {}; 
            if (eventData.accountToken) {
                options.calendarToken = eventData.accountToken;
            }

            await updateProfile(options);
        });
```

All i get is undefined. I've created a trusted domain at my localhost of `localhost:3005` and i've set redirects to my `localhost`... but i'm unsure how i'm supposed to receive my accountToken with this library.

**Comment by fsworld009** [comment]
Hi,

by `localhost:3005` I assume you are running your server at `http://localhost:3005`. However, we only accept https domains as trusted domains. Could you try to setup an https server and run it at `https://localhost:3005`, then try again?

Thanks.

**Comment by fsworld009** [comment]
Hi,

Sorry please ignore my previous response, the trusted domain check shouldn't have any limitation on protocal, so whether your server runs on `http` or `https` it should work.

Could you see if you get anything from `eventData`? Could you also post your App ID here so that I could check your trusted domain settings?

**Comment by floofydoug** [comment]
hey fsworld, appid is `94wojA5tqyjmkaKwkIP9gLZWH4kciuqcsQba5stAhb7oZt2U`
also, get an account number from eventData, but no "account token" like shown in the examples.

**Comment by fsworld009** [comment]
Hi,

I checked your app's config and it looks fine to me. Could you provide more information to me so that I can debug it further:

1. The full launch options object you used to launch the scheduler
2. The full URL, including query params where you launch the scheduler (for example, `http://localhost:3005/index.html?foo=bar`)

Thanks.

**Comment by vinodc** [comment]
@floofydoug Please feel free to reach out to us at support@kloudless.com if this is still a concern and we'd be happy to review it further.
